---
version: '3'
services:
  prometheus:
    image: ${PROM_IMAGE:-prom/prometheus:v2.3.2}
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./prometheus/${PROM_CONFIG:-prom2}-mac.yml:/etc/prometheus/prometheus.yml
    command: ["--config.file=/etc/prometheus/prometheus.yml",
              "--storage.tsdb.path=/prometheus",
              "--storage.tsdb.retention=5m",
              "--web.console.libraries=/usr/share/prometheus/console_libraries",
              "--web.console.templates=/usr/share/prometheus/consoles"]

  node_exporter:
    image: prom/node-exporter
    ports:
      - 127.0.0.1:9100:9100

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - 127.0.0.1:8123:8123
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9009:9009
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml

  clickhouse_exporter:
    image: f1yegor/clickhouse-exporter
    ports:
      - 127.0.0.1:9116:9116
    command: -scrape_uri=http://promhouse_clickhouse_1:8123/

  grafana:
    image: grafana/grafana
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
