---
version: '3'
services:
  prometheus:
    image: ${PROM_IMAGE:-prom/prometheus:v2.0.0}
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./${PROM_CONFIG:-prom2}-mac.yml:/etc/prometheus/prometheus.yml

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - 127.0.0.1:8123:8123
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9009:9009
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./users.xml:/etc/clickhouse-server/users.xml

  clickhouse_exporter:
    image: f1yegor/clickhouse-exporter
    ports:
      - 127.0.0.1:9116:9116
    command: -scrape_uri=http://promhouse_clickhouse_1:8123/

  grafana:
    image: grafana/grafana
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./dashboards:/var/lib/grafana/dashboards
