---
global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: clickhouse
    static_configs:
      - targets: ['127.0.0.1:9116']

  - job_name: promhouse
    metrics_path: /debug/metrics
    static_configs:
      - targets: ['127.0.0.1:7782']

  - job_name: node-exporter
    static_configs:
      - targets: ['127.0.0.1:9100']

remote_read:
  - url: http://127.0.0.1:7781/read

remote_write:
  - url: http://docker.for.mac.host.internal:7781/write
    queue_config:
      capacity: 1000000
      max_shards: 100
      max_samples_per_send: 10000
      batch_send_deadline: 500ms
      max_retries: 10
      min_backoff: 30ms
      max_backoff: 100ms
