dist: trusty
sudo: required
language: go

go:
  - 1.9.x
  - master

services:
  - docker

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose -f misc/docker-compose.yml -p promhouse up -d

script:
  - make init
  - make test-race
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix
