dist: trusty
sudo: required
language: go

go:
  - 1.9.x
  - 1.10.x
  - master

env:
  - PROM_IMAGE=prom/prometheus:v1.8.2 PROM_CONFIG=prom1
  - PROM_IMAGE=prom/prometheus:v2.2.1 PROM_CONFIG=prom2
  - PROM_IMAGE=prom/prometheus:master PROM_CONFIG=prom2

services:
  - docker

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose -f misc/docker-compose.yml -p promhouse up -d

script:
  - make init
  - make test-race
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash) -f cover.out -X fix -e PROM_IMAGE,PROM_CONFIG
